"""auto increment ids

Revision ID: 14286743c273
Revises: 4e3073a0bc68
Create Date: 2023-02-09 13:51:57.901745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14286743c273'
down_revision = '4e3073a0bc68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
