"""Columns update

Revision ID: 4e3073a0bc68
Revises: 3606b157947b
Create Date: 2023-02-08 14:31:37.683700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3073a0bc68'
down_revision = '3606b157947b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('name', sa.String(), nullable=True))
    op.drop_index('ix_items_title', table_name='items')
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.drop_column('items', 'title')
    op.add_column('lists', sa.Column('color', sa.String(), nullable=True, defaut_value='black'))
    op.add_column('lists', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lists', 'order')
    op.drop_column('lists', 'color')
    op.add_column('items', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.create_index('ix_items_title', 'items', ['title'], unique=False)
    op.drop_column('items', 'name')
    # ### end Alembic commands ###
