"""auto increment ids 2

Revision ID: 6698366ec799
Revises: 14286743c273
Create Date: 2023-02-09 13:54:32.797605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6698366ec799'
down_revision = '14286743c273'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
